### ISSUE TITLE
include files not transformed

### ISSUE THREAD

**Issue by miroi** [rbast/freestyle#1]
Hi Rado

~~~
     SUBROUTINE KRCC_INP(WORD,RESET,WORK,LWORK)
#include "ipoist8.inc"
~~~

where "ipoist8.inc"
~~~
      INTEGER*8 ::
! ctccp.inc start
! Hamiltonian
     &             KLSOBEX,KLLSOBEX,KLIBSOBEX,
     &             KLIHIND,KLIHINDOP,KSIGNNHX,KLABEXTP,
~~~

The script does not reformulated include-type files into Fortran90 format, this has to be done manually.

**Comment by bast** [comment]
So what does the script produce and what should it produce instead?

**Comment by miroi** [comment]
OK, closing this issue - it is not purpose of this script to reformat include files (inc, h...). These are to be reformatted manually (unless we would have something in DIRAC  script repository)
